# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 21:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields
import mutual_funds.landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique=True)),
            ],
            options={
                'verbose_name_plural': 'News categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text="Tick to make this entry live (see also the publication date). Note that administrators (like yourself) are allowed to preview inactive entries whereas the general public aren't.")),
                ('pub_date', models.DateTimeField(help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='Publication date')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=mutual_funds.landing.models.UploadToPathAndRename('news'))),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='categories', to='landing.NewsCategory')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
