# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='landing.NewsCategory'),
        ),
    ]
