# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import imagekit.models.fields
import mutual_funds.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=mutual_funds.accounts.models.UploadToPathAndRename('avatars'))),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'мужчина'), (0, 'женщина'), (None, 'не указывать')], null=True, verbose_name='пол')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='день рождения')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('liked_funds', models.ManyToManyField(through='accounts.LikedFund', to='finance.Fund')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='likedfund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='likedfund',
            unique_together=set([('user', 'fund')]),
        ),
    ]
