# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'man'), (0, 'woman'), (None, "don't show")], null=True, verbose_name='gender'),
        ),
    ]
