# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesector',
            name='parsed_name',
            field=models.CharField(help_text='same as at trustnetoffshore', max_length=320),
            preserve_default=False,
        ),
    ]
