# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financesector_parsed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesector',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Tick to make this entry live '),
        ),
    ]
