# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financesector_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financesector',
            options={'ordering': ['name']},
        ),
    ]
