# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 13:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20161123_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesector',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
