# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20161125_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesector',
            name='last_parsed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
