# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financesector_last_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='is_parcing',
            field=models.BooleanField(default=True, help_text='using for parsing'),
        ),
    ]
