# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20161128_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='bloombreg_ticker',
            field=models.CharField(max_length=320, unique=True, validators=[django.core.validators.RegexValidator(message='example: ROBAGED:LX', regex='^\\w*:[A-Z]{2}$')], verbose_name='тикер на Bloomberg'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='isin_ticker',
            field=models.CharField(max_length=320, unique=True, validators=[django.core.validators.RegexValidator(message='example: LU1274831590:EUR', regex='^\\w*:(USD|EUR)$')], verbose_name='тикер ISIN'),
        ),
    ]
