# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-16 20:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20161208_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='launch date'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='bloombreg_ticker',
            field=models.CharField(max_length=320, unique=True, validators=[django.core.validators.RegexValidator(message='example: ROBAGED:LX', regex='^\\w*:[A-Z]{2}$')], verbose_name='Bloomberg ticker'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='isin_ticker',
            field=models.CharField(max_length=320, unique=True, validators=[django.core.validators.RegexValidator(message='example: LU1274831590:EUR', regex='^\\w*:(USD|EUR)$')], verbose_name='ISIN ticker'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=320, unique=True, verbose_name='fund name'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
