# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('fund_manager', models.CharField(max_length=320)),
                ('investment_strategy', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Management companies',
            },
        ),
    ]
